name: Deploy Example to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare public npm config
        run: echo "registry=https://registry.npmjs.org/" > /tmp/npmrc

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        env:
          NPM_CONFIG_USERCONFIG: /tmp/npmrc
        run: npm ci

      - name: Build example
        run: npm run build:example

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example-dist
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com